<a href="https://colab.research.google.com/github/yiwenwangANU/Tensorflow_Certificate/blob/main/Coursera_Course_windowing_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers

In [11]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
  print(val.numpy(), end='')

0123456789

In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for windowed_dataset in dataset:
  for val in windowed_dataset:
    print(val.numpy(), end='')
  print()

01234
12345
23456
34567
45678
56789
6789
789
89
9


In [16]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for windowed_dataset in dataset:
  for val in windowed_dataset:
    print(val.numpy(), end='')
  print()

01234
12345
23456
34567
45678
56789


In [21]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.batch(5)
for batch in dataset:
  print(batch)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


In [27]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int64)
tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int64)
tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


In [31]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
for X, y in dataset:
  print(X, y)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int64) tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64) tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64) tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int64) tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64) tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int64) tf.Tensor(9, shape=(), dtype=int64)


In [32]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
dataset = dataset.shuffle(buffer_size=10)
for X, y in dataset:
  print(X, y)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int64) tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int64) tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64) tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64) tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64) tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int64) tf.Tensor(7, shape=(), dtype=int64)


In [34]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1]))
dataset = dataset.shuffle(buffer_size=2)
dataset = dataset.batch(2).prefetch(tf.data.AUTOTUNE)
for X, y in dataset:
  print(X, y)

tf.Tensor(
[[0 1 2 3]
 [2 3 4 5]], shape=(2, 4), dtype=int64) tf.Tensor([4 6], shape=(2,), dtype=int64)
tf.Tensor(
[[1 2 3 4]
 [4 5 6 7]], shape=(2, 4), dtype=int64) tf.Tensor([5 8], shape=(2,), dtype=int64)
tf.Tensor(
[[5 6 7 8]
 [3 4 5 6]], shape=(2, 4), dtype=int64) tf.Tensor([9 7], shape=(2,), dtype=int64)


In [42]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
  dataset = tf.data.Dataset.from_tensor_slices(series)
  dataset = dataset.window(window_size+1, shift=1, drop_remainder=True)
  dataset = dataset.flat_map(lambda window: window.batch(window_size+1))
  dataset = dataset.map(lambda window: (window[:-1], window[-1]))
  dataset = dataset.shuffle(buffer_size=shuffle_buffer)
  dataset = dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE)
  return dataset

In [44]:
dataset = windowed_dataset(tf.range(10),
                            window_size=4,
                            batch_size=2,
                            shuffle_buffer=2)
for X, y in dataset:
  print(X, y)

tf.Tensor(
[[1 2 3 4]
 [0 1 2 3]], shape=(2, 4), dtype=int32) tf.Tensor([5 4], shape=(2,), dtype=int32)
tf.Tensor(
[[3 4 5 6]
 [4 5 6 7]], shape=(2, 4), dtype=int32) tf.Tensor([7 8], shape=(2,), dtype=int32)
tf.Tensor(
[[2 3 4 5]
 [5 6 7 8]], shape=(2, 4), dtype=int32) tf.Tensor([6 9], shape=(2,), dtype=int32)
